### ISSUE TITLE
bug: `model_config` with `ExprTuple` cannot be interpreted

### ISSUE THREAD

**Issue by miili** [mkdocstrings/griffe-pydantic#13]
### Description of the bug
`ExprTuple` in `ConfigDict` cannot be interpreted and crashes griffe-pydantic.

### To Reproduce
```py
from pydantic import BaseModel, ConfigDict
from functools import cached_property

class Model(BaseModel)
    model_config = ConfigDict(ignored_types=(cached_property,))
```

**Comment by pawamoy** [comment]
Hi @miili, thanks for the report.

I cannot reproduce the issue you describe, though note that you're missing a colon after your class definition. Please provide the complete traceback (error message) to see if this is the actual issue (`SyntaxError`) :slightly_smiling_face:

**Comment by miili** [comment]
Well, this was from the top of my head. Add a colon.

**Comment by pawamoy** [comment]
OK, please reopen when you have a minimum reproducible example, thanks :slightly_smiling_face:
