### ISSUE TITLE
does not render using `griffe-pydantic` if imported with `__all__`

### ISSUE THREAD

**Issue by butterlyn** [mkdocstrings/griffe-pydantic#5]
When importing a Pydantic model from a private module to a public module, the class can be rendered in MkDocs by adding it to the `__all__` dunder variable. However, this renders Pydantic model classes as regular classes, ignoring changes expected by having `griffe-pydantic` installed.

When rendering in MkDocs directly in the public module (without importing from a private module), the Pydantic model renders with `griffe-pydantic` as expected.

**Comment by pawamoy** [comment]
Hi @butterlyn, thanks for the report. It's quite curious indeed, let me investigate.

**Comment by pawamoy** [comment]
Sorry but I cannot reproduce the issue you describe. Could you please provide a minimal reproduction example?

**Comment by pawamoy** [comment]
@butterlyn could you let me know if you still have this issue with v1.1.0?

**Comment by pawamoy** [comment]
Cannot reproduce and no update, closing for now, feel free to comment further!
